#!/bin/bash


function mount_nodejs {
	RC_PROFILE="/root/.yrc_profile"

	[ ! -f "${RC_PROFILE}" ] && echo "${RC_PROFILE} does not exist." && exit 1
	[ "" == "${RC_ROOT}" ] && echo "RC_ROOT variable is not specified" && exit 1

	NODE_RUMTIME_VERSION=$(cat ${RC_PROFILE} | grep "^nodejs_runtime" | awk -F '\t' '{print $2}')
	NODE_MODULE_PROFILE=$(cat ${RC_PROFILE} | grep "^nodejs_module_profile" | awk -F '\t' '{print $2}')
	NODE_VERSION=$(cat ${RC_PROFILE} | grep "^nodejs_version" | awk -F '\t' '{print $2}')

	# Mount nodejs runtime to /root/.nodenv
	#
	MOUNT_DIR=true ${RC_ROOT}/scripts/nodejs_mount ${NODE_RUMTIME_VERSION}
	cd ~

	# Initiate .nodenv
	#
	export PATH="/root/.nodenv/bin:$PATH"
	eval "$(nodenv init -)"
	nodenv global ${NODE_VERSION}

	RUNTIME_PATH=$(dirname $(mount | grep .nodenv | awk '{print $1}'))

	LS_VERSION=$(cat ${RUNTIME_PATH}/configs | grep -i "livescript" | awk '{print $3}')

	export PS1="\t \[\e[33m\]\w\[\e[m\] [node:\[\e[32m\]${NODE_VERSION}\[\e[m\] livscript:\[\e[36m\]${LS_VERSION}\[\e[m\]] [\$?]\n\\$ \[$(tput sgr0)\]"
	export PATH=$PATH:${RC_ROOT}/scripts

	export YRC_NODE_RUNTIME_PATH=${RUNTIME_PATH}
	export YRC_NODE_RUNTIME=${NODE_RUMTIME_VERSION}
	export YRC_NODE_VERSION=${NODE_VERSION}
	export YRC_NODE_MODULE_PROFILE=${NODE_MODULE_PROFILE}

	CURRENT=$(pwd)
	cd ${RUNTIME_PATH}
	cd ../../../../../
	export YRC_ROOT=$(pwd)
	cd ${CURRENT}
}
