#!/bin/bash

function install_module {
	MODULE=$1
	VERSION=$2
	CURRENT=$(pwd)

	[ "" == "${YRC_ROOT}" ] && echo "YRC_ROOT isn't specified" && exit 1
	[ "" == "${YRC_NODE_VERSION}" ] && echo "YRC_NODE_VERSION isn't specified" && exit 1
	[ "" == "${OS_NAME}" ] && echo "OS_NAME isn't specified" && exit 1
	[ "" == "${OS_ARCH}" ] && echo "OS_ARCH isn't specified" && exit 1

	TMP=$(mktemp)
	npm view ${MODULE} > ${TMP}
	EXIT_CODE=$?
	[ "0" != "${EXIT_CODE}" ] && echo "failed to retrieve basic information of module [${MODULE}]" && exit 1

	LATEST_VERSION=$(cat ${TMP} | jq .version | sed 's/"//g')
	rm -f ${TMP}

	[ "" == "${VERSION}" ] && VERSION=${LATEST_VERSION}

	MODULE_DIR="${YRC_ROOT}/nodejs/modules/${OS_NAME}/${OS_ARCH}/${YRC_NODE_VERSION}/${MODULE}/${VERSION}"
	MODULE_INSTALL_PRE_CMD="npm config set user 0 && npm config set unsafe-perm true"
	MODULE_INSTALL_CMD="npm install ${MODULE}@${VERSION}"

	[ -d "${MODULE_DIR}" ] && echo "${MODULE_DIR} exists" && exit 0

	cd /tmp

	echo "running: ${MODULE_INSTALL_PRE_CMD}"
	${MODULE_INSTALL_PRE_CMD} > /dev/null

	echo "running: ${MODULE_INSTALL_CMD}"
	${MODULE_INSTALL_CMD} > /dev/null
	EXIT_CODE=$?

	if [ "0" != "${EXIT_CODE}" ]; then
		echo "failed to install ${MODULE}@${VERSION}"
	else
		mkdir -p ${MODULE_DIR}
		cp /tmp/node_modules/${MODULE}/* ${MODULE_DIR} -R
		rm -rf /tmp/node_modules/${MODULE}
		echo "install ${MODULE} (version: ${VERSION}) at ${MODULE_DIR} successfully"
	fi
}

CURRENT=$(pwd)
cd $(dirname $0)
cd ..
RC_ROOT=$(pwd)
RC_SCRIPT_DIR="${RC_ROOT}/scripts"
cd ${CURRENT}

source ${RC_SCRIPT_DIR}/funcs

if [ "" == "$(which npm)" ]; then
	initiateVariables
	[ "" == "${NODE_RUNTIME}" ] && echo "missing npm, and NODE_RUNTIME is not specified" && exit 1
	NEED_UNMOUNT="true"
	${RC_SCRIPT_DIR}/unhook
	NODE_RUNTIME=${NODE_RUNTIME} ${RC_SCRIPT_DIR}/hook
	RC_ROOT=${RC_ROOT} source ${RC_SCRIPT_DIR}/funcs_bashrc && mount_nodejs
else
	initiateOsVariables
	NEED_UNMOUNT="false"
fi

for p in "$@"
do
	MODULE=$(echo $p | awk -F'@' '{print $1}')
	VERSION=$(echo $p | awk -F'@' '{print $2}')
	install_module ${MODULE} ${VERSION}
done

[ "true" == "${NEED_UNMOUNT}" ] && ${RC_SCRIPT_DIR}/unhook
